# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E Labels Tests

on:
  pull_request:
    branches: [ master ]
env:
  CYPRESS_USERNAME: ${{secrets.CYPRESS_USERNAME}}
  CYPRESS_USER_PASSWORD: ${{secrets.CYPRESS_USER_PASSWORD}}

jobs:
  cypress-run:

    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install 
        run: npm ci
      - name: Export PR Labels
        uses: PedroJPerez/my-actions/move-test-plan@v1.22
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Login
        run: echo $LOGIN
      - name: Echo Contact Card
        run: echo $CONTACT_CARD
      - name: Get Cypress info
        id: cypress-info
        run: |
          echo ::set-output name=version::$(jq -r .devDependencies.cypress ./package.json)
          echo ::set-output name=cache::$(npx cypress cache path)
      - name: Cypress Verify Output
        run: echo "The output is ${{ steps.cypress-info.outputs.version }}"
      - name: Comment Code Coverage
        uses: mshick/add-pr-comment@v1
        with:
          message: Cypress Version  ${{ steps.cypress-info.outputs.version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build script
        run: source ./cypress/script.sh
      - name: PRINT SCRIPT OUTPUT
        run: echo $SUMMARY
      - name: Execute Cypress
        uses: cypress-io/github-action@v4
        with: 
          browser: chrome
          spec: cypress/integration/**

