name: E2E Testing
on: pull_request
env:
  CYPRESS_USERNAME: ${{secrets.CYPRESS_USERNAME}}
  CYPRESS_USER_PASSWORD: ${{secrets.CYPRESS_USER_PASSWORD}}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

  e2e_tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [testrunOne, testrunTwo, TestrunThree]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/${{ matrix.containers }}/**
          working-directory: src
          browser: chrome